# /opt/kleinanzeigen-api/docker-compose.yml
services:
  backend:
    container_name: kleinanzeigen-api
    build:
      context: .
      dockerfile: Dockerfile       
    ports:
      - "8000:8000"
      - "8001:8001"
    shm_size: "1gb"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8001
    restart: unless-stopped

  frontend:
    container_name: kleinanzeigen-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BACKEND_URL=http://backend:8000
    environment:
      - API_BASE_URL=http://backend:8000
      - BACKEND_URL=http://backend:8000
      - PORT=3000
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "3001:3000"
    depends_on:
      - backend
    restart: unless-stopped
